/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 86
#define YY_END_OF_BUFFER 87
static yyconst short int yy_accept[226] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       87,   85,   83,   84,   85,   51,   38,   39,   29,   27,
       46,   28,   85,   30,   47,   47,   45,   44,   34,   37,
       33,   85,   71,   71,   42,   85,   43,   71,   71,   71,
       71,   71,   26,   71,   24,   71,   40,   41,   74,   76,
       85,   78,   78,   85,   78,   53,   67,   85,   54,   68,
       32,   69,   77,   73,   69,   49,   50,   72,   72,   72,
       47,   36,   31,   35,   52,    0,    0,    0,   71,   71,
       85,   71,   11,   71,   71,   71,   71,    8,   13,   71,
       71,   71,   71,   74,   75,   78,   78,   80,   80,    0,

       82,   78,   53,   62,   61,   66,   64,   63,   55,   56,
       57,   58,   59,   60,    0,    0,   69,   69,    0,   70,
       48,    0,    0,    0,    0,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   12,    1,   71,   71,   71,   71,
       66,   65,   70,   70,   15,    0,    0,    0,   71,   71,
       71,   71,   71,   71,    3,    9,   21,   71,   25,   71,
       71,   71,   66,   65,   70,    0,    0,    0,   71,   71,
       71,   22,    6,   71,   18,   71,   71,   71,   10,    0,
        0,    0,   71,   71,   71,   71,   71,   71,   71,    0,
        0,    0,    5,   71,   71,   71,   71,   71,   71,    0,

        0,    0,   71,   71,    4,   19,   71,   23,    0,    0,
       17,   71,    2,   20,    0,   14,   71,    0,   71,    0,
        7,    0,    0,   16,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    1,    1,    1,    1,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   17,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   26,   27,   28,   29,
       30,   30,   31,   30,   30,   32,   30,   33,   30,   30,
       30,   30,   34,   30,   30,   30,   30,   35,   30,   30,
       36,   37,   38,    1,   30,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   30,   30,   48,   49,   50,
       51,   52,   30,   53,   54,   55,   56,   57,   58,   59,
       60,   30,   61,    1,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[63] =
    {   0,
        1,    2,    1,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    5,    1,    6,    6,    6,    1,    1,    1,
        1,    1,    1,    1,    6,    6,    6,    6,    6,    7,
        7,    7,    7,    7,    7,    1,    2,    1,    6,    6,
        6,    6,    6,    6,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        1,    1
    } ;

static yyconst short int yy_base[238] =
    {   0,
        0,    0,   61,   62,   63,   64,   65,   66,   72,   73,
      392,  393,  393,  393,  370,  393,  393,  393,  393,  393,
      393,  393,   65,   74,   76,   99,  393,  393,  369,  368,
      367,   79,    0,  353,  393,  336,  393,  339,  333,   37,
       46,   46,  332,  339,  331,  334,  393,  393,    0,  393,
       67,  377,  376,  104,   74,    0,  393,  138,  393,  393,
      393,  121,  393,  393,  130,  153,  170,  364,  117,  201,
      191,  393,  393,  393,  393,  326,   58,  322,    0,  178,
      393,  335,    0,  319,  316,  320,  317,    0,  314,  318,
      328,  312,  318,    0,  393,  362,  361,  393,  393,  146,

      393,  360,    0,  393,  393,  105,  393,  393,  393,  393,
      393,  393,  393,  393,    0,  208,  393,  220,  124,  237,
        0,  319,  308,  304,  307,  304,  309,  305,  303,  108,
      300,  309,  302,  311,    0,    0,  304,  306,  300,  298,
      141,    0,  240,  328,  393,  292,  285,  267,  230,  241,
      225,  234,  223,  224,    0,    0,    0,  221,    0,  121,
      230,  231,  393,  393,  393,  230,  219,  228,  231,  213,
      224,    0,    0,  218,    0,  212,  208,  210,    0,  210,
      214,  198,  187,  199,  194,  188,  185,  185,  188,  179,
      182,  160,    0,  160,  159,  156,  140,  144,  152,  142,

      149,  129,  134,  127,    0,    0,  134,    0,  121,  128,
      393,  128,    0,    0,  123,  393,   99,   73,   65,   76,
        0,   54,   45,  393,  393,  284,  291,  298,  305,  308,
      310,  317,  324,  331,  338,   80,   71
    } ;

static yyconst short int yy_def[238] =
    {   0,
      225,    1,  226,  226,  227,  227,  228,  228,  229,  229,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  230,  230,  225,  225,  225,  225,
      225,  225,  231,  231,  225,  225,  225,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  225,  225,  232,  225,
      225,  233,  233,  234,  233,  235,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  230,  230,  230,  230,  230,
      230,  225,  225,  225,  225,  225,  225,  225,  231,  231,
      225,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  232,  225,  233,  233,  225,  225,  234,

      225,  233,  235,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  236,  225,  225,  225,  225,  230,
       70,  225,  225,  225,  225,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      225,  237,  225,  230,  225,  225,  225,  225,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  225,  225,  225,  225,  225,  225,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  225,
      225,  225,  231,  231,  231,  231,  231,  231,  231,  225,
      225,  225,  231,  231,  231,  231,  231,  231,  231,  225,

      225,  225,  231,  231,  231,  231,  231,  231,  225,  225,
      225,  231,  231,  231,  225,  225,  231,  225,  231,  225,
      231,  225,  225,  225,    0,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225
    } ;

static yyconst short int yy_nxt[456] =
    {   0,
       12,   13,   14,   15,   12,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   26,   27,   28,   29,
       30,   31,   12,   32,   33,   33,   33,   33,   33,   33,
       33,   33,   34,   33,   33,   35,   36,   37,   33,   33,
       38,   39,   40,   41,   33,   33,   42,   43,   33,   33,
       33,   33,   44,   33,   33,   45,   33,   46,   33,   33,
       47,   48,   50,   50,   53,   53,   13,   13,   95,   57,
       57,   54,   54,   13,   13,   97,  164,   60,   60,   62,
       62,   62,   63,   75,   84,  142,   85,   64,   65,   88,
       66,   66,   67,   86,  224,   89,   87,   51,   51,   55,

       55,   58,   58,   69,  223,   99,  123,  124,   58,   58,
       70,   65,  100,   71,   71,   71,   81,  101,   69,  141,
      141,   76,  222,  102,  221,   77,   69,  220,  119,  225,
       78,  120,  120,  120,   70,   62,   62,   62,  143,  143,
      143,   69,  104,  105,  118,  118,  118,   99,  116,  117,
      153,  219,  106,  106,  100,  163,  163,  116,  117,  101,
      107,  218,  154,  116,  117,   65,  217,   66,   66,   67,
      216,  176,  116,  117,  108,  215,  214,  109,  177,  213,
       69,  110,   65,  212,   67,   67,   67,  111,  211,  210,
      112,  209,  113,  208,  114,   69,  115,   69,  207,  206,

      205,  204,  126,   65,  127,   71,   71,   71,  128,  129,
      203,  130,   69,  225,  202,  121,  121,  121,   69,  119,
      201,  200,  143,  143,  143,  121,  121,  121,  121,  121,
      199,  198,  197,   69,  118,  118,  118,  196,  195,  121,
      121,  121,  121,  121,  121,  194,  193,  116,  117,  225,
      192,  120,  120,  120,  143,  143,  143,  191,  190,  189,
      188,  187,  116,  117,  186,  144,  185,  184,  165,  183,
      182,  181,  180,  179,  178,  175,  174,  173,  172,  171,
      144,  170,  169,  165,   49,   49,   49,   49,   49,   49,
       49,   52,   52,   52,   52,   52,   52,   52,   56,   56,

       56,   56,   56,   56,   56,   59,   59,   59,   59,   59,
       59,   59,   68,   68,   68,   79,   79,   94,  168,   94,
       94,   94,   94,   94,   96,   96,   96,  167,   96,   96,
       96,   98,   98,   98,   98,   98,   98,   98,  103,  166,
      225,  103,  103,  103,  103,  162,  161,  160,  159,  158,
      157,  156,  155,  152,  151,  150,  149,  148,  147,  146,
      145,   97,   97,   97,  140,  139,  138,  137,  136,  135,
      134,  133,  132,  131,  125,  122,  225,   97,   97,   93,
       92,   91,   90,   83,   82,   81,   80,   74,   73,   72,
       61,  225,   11,  225,  225,  225,  225,  225,  225,  225,

      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225
    } ;

static yyconst short int yy_chk[456] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    6,    7,    8,   51,    7,
        8,    5,    6,    9,   10,   55,  237,    9,   10,   23,
       23,   23,   24,   32,   40,  236,   40,   24,   25,   42,
       25,   25,   25,   41,  223,   42,   41,    3,    4,    5,

        6,    7,    8,   25,  222,   54,   77,   77,    9,   10,
       25,   26,   54,   26,   26,   26,   51,   54,   25,  106,
      106,   32,  220,   55,  219,   32,   26,  218,   69,   69,
       32,   69,   69,   69,   25,   62,   62,   62,  119,  119,
      119,   26,   58,   58,   65,   65,   65,  100,   62,   62,
      130,  217,   58,   58,  100,  141,  141,   65,   65,  100,
       58,  215,  130,   62,   62,   66,  212,   66,   66,   66,
      210,  160,   65,   65,   58,  209,  207,   58,  160,  204,
       66,   58,   67,  203,   67,   67,   67,   58,  202,  201,
       58,  200,   58,  199,   58,   66,   58,   67,  198,  197,

      196,  195,   80,   71,   80,   71,   71,   71,   80,   80,
      194,   80,   67,   70,  192,   70,   70,   70,   71,  116,
      191,  190,  116,  116,  116,   70,   70,   70,   70,   70,
      189,  188,  187,   71,  118,  118,  118,  186,  185,   70,
       70,   70,   70,   70,   70,  184,  183,  118,  118,  120,
      182,  120,  120,  120,  143,  143,  143,  181,  180,  178,
      177,  176,  118,  118,  174,  120,  171,  170,  143,  169,
      168,  167,  166,  162,  161,  158,  154,  153,  152,  151,
      120,  150,  149,  143,  226,  226,  226,  226,  226,  226,
      226,  227,  227,  227,  227,  227,  227,  227,  228,  228,

      228,  228,  228,  228,  228,  229,  229,  229,  229,  229,
      229,  229,  230,  230,  230,  231,  231,  232,  148,  232,
      232,  232,  232,  232,  233,  233,  233,  147,  233,  233,
      233,  234,  234,  234,  234,  234,  234,  234,  235,  146,
      144,  235,  235,  235,  235,  140,  139,  138,  137,  134,
      133,  132,  131,  129,  128,  127,  126,  125,  124,  123,
      122,  102,   97,   96,   93,   92,   91,   90,   89,   87,
       86,   85,   84,   82,   78,   76,   68,   53,   52,   46,
       45,   44,   43,   39,   38,   36,   34,   31,   30,   29,
       15,   11,  225,  225,  225,  225,  225,  225,  225,  225,

      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
#define INITIAL 0
/*Опции*/
#define YY_NEVER_INTERACTIVE 1
/*Именованные шаблоны*/
/*Стартовые состояния*/
#define LINE_COMMENT 1

#define MULTILINE_COMMENT 2

#define STRING 3

#define CHAR 4

/*Подключение библиотек*/
#line 17 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
    #include <stdio.h>
    #include <string.h>
    #include <stdlib.h>

    int isContainsSymbol(char *string, char symbol);
    void removeSymbol(char *string, char symbol);
    void removeFloatSuffix(char *string);
#line 563 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 26 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"


    char tmp[10000];
    int rowCount = 1;




#line 719 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 226 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 393 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 34 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 35 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 36 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 37 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 38 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 39 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 40 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 41 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 42 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 43 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 44 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 46 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 47 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 48 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 49 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 50 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 51 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 52 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 53 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 54 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 55 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 56 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 57 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 58 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 59 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found keyword: %s\n", yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 62 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found arithmetic operation: %s\n", yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 63 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found arithmetic operation: %s\n", yytext);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 64 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found arithmetic operation: %s\n", yytext);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 65 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found arithmetic operation: %s\n", yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 68 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found comparison operation: %s\n", yytext);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 69 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found comparison operation: %s\n", yytext);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 70 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found comparison operation: %s\n", yytext);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 71 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found comparison operation: %s\n", yytext);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 72 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found comparison operation: %s\n", yytext);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 73 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found comparison operation: %s\n", yytext);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found assignment operation: %s\n", yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 79 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found bracket: %s\n", yytext);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 80 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found bracket: %s\n", yytext);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 81 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found bracket: %s\n", yytext);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 82 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found bracket: %s\n", yytext);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 83 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found bracket: %s\n", yytext);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 84 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found bracket: %s\n", yytext);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 87 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found delimiter: %s\n", yytext);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 88 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found delimiter: %s\n", yytext);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 89 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found delimiter: %s\n", yytext);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 92 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found integer: %d\n", atoi(yytext));}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 93 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    char* a;
    long number = strtol(yytext+2, &a,16);
    printf("Found hexadecimal number: %d\n", number);
    }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 98 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    char *a;
    long number = strtol(yytext+2, &a,8);
    printf("Found octal number: %d\n", number);
    }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 103 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    printf("ERROR! Incorrect octal number: %s in row: %d\n", yytext, rowCount);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 107 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
strcpy(tmp,""); BEGIN(CHAR);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 108 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
strcpy(tmp,""); BEGIN(STRING);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 109 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
strcat(tmp,yytext);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 110 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
strcat(tmp,yytext);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 111 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
strcat(tmp,"\b");
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 112 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
strcat(tmp,"\f");
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 113 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
strcat(tmp,"\n");
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 114 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
strcat(tmp,"\r");
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 115 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
strcat(tmp,"\t");
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 116 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
strcat(tmp,"\v");
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 117 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
strcat(tmp,"\'");
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 118 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
strcat(tmp,"\"");
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 119 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
strcat(tmp,"\\");
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 120 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
strcat(tmp,"\?");
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 121 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    char dig[2];
    char *a;
    dig[0]=strtol(yytext+2, &a, 16);
    dig[1]='\0';
    strcat(tmp, dig);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 127 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    char dig[2];
    char *a;
    dig[0]=strtol(yytext+1, &a, 8);
    dig[1]='\0';
strcat(tmp, dig);}
	YY_BREAK
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(CHAR):
#line 133 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! haven't found closing quotes in row: %d\n", rowCount); BEGIN(INITIAL);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 134 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found String literal: %s\n",tmp);BEGIN(INITIAL);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 135 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    if(strlen(tmp) != 1)
    {
        printf("ERROR! char length != 1 in row: %d\n", rowCount);BEGIN(INITIAL);
    }
    else
    {
        printf("Found Char literal: %s\n",tmp);BEGIN(INITIAL);
    }
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 148 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    strcpy(tmp, yytext);
    removeFloatSuffix(tmp);
    printf("Found float constant: %f\n", (float)atof(tmp));
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 154 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    strcpy(tmp, yytext);
    removeFloatSuffix(tmp);
    printf("Found float constant: %f\n", (float)atof(tmp));
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 160 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found identifier: %s\n", yytext);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 161 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Incorrect identifier name: %s in row: %d\n", yytext, rowCount);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 164 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{tmp[0] = '\0'; BEGIN(LINE_COMMENT);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 165 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{strcat(tmp, yytext);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 166 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{ rowCount++; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 167 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found comment: %s\n", tmp); BEGIN(INITIAL); rowCount++; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 169 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{tmp[0] = '\0'; BEGIN(MULTILINE_COMMENT);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 170 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{strcat(tmp, yytext);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 171 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{rowCount++; strcat(tmp, yytext);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 172 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{strcat(tmp, yytext);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 173 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{rowCount++; strcat(tmp, yytext);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 174 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("Found comment: %s\n", tmp);BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 176 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Multiline comment \"%s\" isn't closed in row: %d\n", tmp, rowCount); BEGIN(INITIAL);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 178 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{rowCount++;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 180 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("", yytext);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 182 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("unrecognized element: %s\n", yytext);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 184 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
ECHO;
	YY_BREAK
#line 1278 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(LINE_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 226 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 226 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 225);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 184 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"


//Проверка на содержание символа в строке
int isContainsSymbol(char *string, char symbol)
{
    return strchr(string, symbol) != NULL;
}

//Удаление первого вхождения символа в строку
void removeSymbol(char *string, char symbol)
{
    if (isContainsSymbol(string, symbol))
    {
        char* pointer = strchr(string, symbol);
        int symbolPos = pointer - string;
        int len = strlen(string);
        for (int i=symbolPos; i < len; i++)
        {
            string[i] = string[i+1];
        }
        string[len-1] = '\0';
    }
}

//Удаление суффикса float
void removeFloatSuffix(char *string)
{
    if (isContainsSymbol(string, 'f') || isContainsSymbol(string, 'F'))
    {
        removeSymbol(string, 'f');
        removeSymbol(string, 'F');
    }
}

int main(int argc, char* argv[])
{
    if ( argc > 1 )
            yyin = fopen( argv[1], "r" );
    else
            yyin = stdin;

    yylex();
}
