/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
static yyconst short int yy_accept[233] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      100,   98,   97,   95,   98,   62,   61,   47,   48,   30,
       28,   55,   29,   45,   31,   56,   56,   54,   53,   37,
       40,   36,   98,   86,   51,   98,   52,   86,   86,   86,
       86,   86,   21,   86,   86,   19,   86,   86,   49,   50,
       90,   98,   90,   64,   81,   82,   98,   65,   83,   95,
       35,   43,   32,   41,   33,   42,   46,   84,   89,   88,
       44,   84,   59,   60,   87,   87,   87,   56,   39,   34,
       38,   63,    0,    0,    0,    0,    0,   86,   96,   86,
        6,   86,   86,   86,   86,   25,    3,    8,   86,   86,

       86,   86,   86,   86,   86,   90,   91,   92,   93,    0,
       94,   91,   64,   73,   72,   75,   80,   74,   66,   67,
       68,   69,   70,   71,   79,    0,   84,   88,   88,   84,
        0,   85,   57,   58,    0,    0,    0,    0,    0,    0,
       86,   86,   86,   86,    7,    1,   86,   86,   86,   86,
       86,   86,   86,   86,   80,   79,   76,   78,   85,   85,
        0,   10,    0,    0,    0,    0,    2,    4,   17,   86,
       20,   86,   86,   23,   86,   86,   27,   86,   80,   77,
       78,   85,    0,    0,    0,    0,    0,   14,   86,   86,
       86,   24,   86,    5,   26,    0,    0,    0,    0,   86,

       86,   22,   86,    0,    0,    0,    0,   86,   86,   86,
        0,    0,    0,    0,   15,   86,   18,    0,    0,   12,
        0,   16,    0,    9,    0,    0,   13,    0,    0,    0,
       11,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    1,    1,    1,    1,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   17,   17,   18,   19,   20,
       21,   22,    1,   23,   24,   24,   24,   24,   25,   26,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   28,   27,   27,
       29,   30,   31,    1,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   27,   27,   42,   43,   44,
       45,   46,   27,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,    1,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    2,    1,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    5,    1,    6,    6,    6,    1,    1,    1,
        1,    1,    1,    6,    6,    6,    7,    7,    1,    3,
        1,    7,    6,    6,    6,    6,    6,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    1,    1
    } ;

static yyconst short int yy_base[244] =
    {   0,
        0,    0,   56,   57,   58,   59,   65,   66,   68,   72,
      437,  438,  438,  433,  414,  438,  438,  438,  438,  413,
       59,  438,   63,   66,   83,   90,   95,  438,  438,  412,
      411,  410,   88,    0,  438,  428,  438,  389,  383,   34,
       49,   78,  382,  389,   63,  381,  379,  383,  438,  438,
      420,  117,  419,    0,  438,  438,  142,  438,  438,  417,
      438,  438,  438,  438,  438,  438,  438,  124,  438,  389,
      438,  162,  138,  181,  405,  154,  204,  188,  438,  438,
      438,  438,  375,  372,   94,  368,  360,    0,  438,  380,
        0,  364,  361,  365,  362,    0,    0,  359,  363,   68,

      364,  359,  356,  362,  361,  399,  438,  438,  438,  119,
      438,  438,    0,  438,  438,  130,  144,  438,  438,  438,
      438,  438,  438,  438,  245,  199,  438,  370,   60,  248,
      166,  274,    0,  298,  366,  362,  339,  330,  333,  322,
      283,  292,  285,  294,    0,    0,  287,  289,  271,  282,
      282,  277,  281,  269,  158,  438,  295,    0,  278,  296,
      260,  438,  265,  269,  259,  254,    0,    0,    0,  253,
        0,   90,  254,    0,  252,  259,    0,  260,  438,  438,
      438,  438,  248,  255,  241,  247,  237,    0,  232,  228,
      228,    0,  224,    0,  438,  224,  228,  188,  197,  191,

      186,    0,  189,  187,  190,  173,  169,  158,  161,  172,
      163,  167,  138,  149,    0,  148,    0,  135,  131,  438,
      110,    0,  123,  438,  115,   81,  438,   83,   64,   55,
      438,  438,  336,  343,  350,  353,  355,  362,  369,  376,
      383,  390,   73
    } ;

static yyconst short int yy_def[244] =
    {   0,
      232,    1,  233,  233,  234,  234,  235,  235,  234,  234,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  236,  236,  232,  232,  232,
      232,  232,  232,  237,  232,  232,  232,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  232,  232,
      238,  239,  238,  240,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  241,
      232,  232,  236,  236,  236,  236,  232,  236,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  237,  232,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,

      237,  237,  237,  237,  237,  238,  232,  232,  232,  239,
      232,  232,  240,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  242,  232,  232,  241,  241,  232,
      232,  236,   77,   77,  232,  232,  232,  232,  232,  232,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  232,  232,  243,  243,  232,  236,
      232,  232,  232,  232,  232,  232,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  237,  237,  237,
      237,  237,  237,  237,  232,  232,  232,  232,  232,  237,

      237,  237,  237,  232,  232,  232,  232,  237,  237,  237,
      232,  232,  232,  232,  237,  237,  237,  232,  232,  232,
      232,  237,  232,  232,  232,  232,  232,  232,  232,  232,
      232,    0,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232
    } ;

static yyconst short int yy_nxt[496] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   27,   28,   29,   30,
       31,   32,   33,   34,   34,   34,   34,   34,   35,   36,
       37,   34,   34,   34,   38,   39,   40,   41,   34,   34,
       42,   43,   34,   34,   34,   34,   44,   45,   34,   46,
       47,   48,   34,   34,   34,   49,   50,   13,   13,   55,
       55,  128,   56,   56,   52,   52,   55,   55,   63,   55,
       59,   59,   56,   55,   65,   92,   56,   93,  181,   64,
       68,   68,   68,   66,   67,   53,   53,   57,   57,  129,
       94,   69,   82,   95,   57,   57,   70,   57,  231,  101,

      148,   57,   72,   71,   73,   73,   74,   72,  230,   78,
       78,   78,  102,   96,   76,   97,  149,   77,  109,   76,
      109,   98,   83,  229,   84,  110,   76,  110,   85,  228,
      111,   76,  111,   86,  189,   87,  137,  138,   68,   68,
       68,  190,   77,   89,  155,  155,  114,  115,  126,  127,
       72,  227,   73,   73,   74,  226,  116,  117,  155,  155,
      126,  127,   76,  131,  225,  131,  232,  224,  132,  132,
      132,  118,  179,  179,   76,  119,  130,  130,  130,  120,
      159,  159,  159,  223,  222,  121,  126,  127,  122,  221,
      123,  220,  124,   72,  125,   74,   74,   74,  126,  127,

       72,  219,   78,   78,   78,   76,  218,  217,  131,  216,
      131,  215,   76,  159,  159,  159,  214,   76,  133,  133,
      133,  213,  212,  211,   76,  210,  209,  133,  133,  133,
      134,  134,  208,  207,  206,   75,  133,  133,  133,  133,
      133,  133,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  157,
      158,  158,  130,  130,  130,  205,  204,  203,  158,  158,
      158,  202,  126,  127,  201,  200,  199,  158,  158,  158,
      158,  158,  158,  198,  126,  127,  232,  197,  132,  132,
      132,  196,  159,  159,  159,  195,  194,  193,  192,  160,

      191,  188,  187,  182,  186,  185,  184,  183,  232,  180,
      178,  160,  134,  134,  134,  182,  177,  176,  175,  174,
      173,  134,  134,  134,  172,  171,  170,  169,  168,  167,
      134,  134,  134,  134,  134,  134,   51,   51,   51,   51,
       51,   51,   51,   54,   54,   54,   54,   54,   54,   54,
       58,   58,   58,   58,   58,   58,   58,   75,   75,   75,
       88,   88,  106,  106,  106,  166,  106,  106,  106,  108,
      108,  108,  108,  108,  108,  108,  113,  165,  164,  113,
      113,  113,  113,  128,  163,  128,  128,  128,  128,  128,
      156,  156,  156,  156,  156,  156,  156,  162,  161,  129,

      107,  154,  153,  152,  151,  150,  147,  146,  145,  144,
      143,  142,  141,  140,  139,  136,  135,  232,  129,   60,
      112,  107,  105,  104,  103,  100,   99,   91,   90,   89,
       81,   80,   79,   62,   61,   60,  232,   11,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232

    } ;

static yyconst short int yy_chk[496] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
        6,  129,    5,    6,    3,    4,    7,    8,   21,    9,
        7,    8,    9,   10,   23,   40,   10,   40,  243,   21,
       24,   24,   24,   23,   23,    3,    4,    5,    6,  129,
       41,   25,   33,   41,    7,    8,   25,    9,  230,   45,

      100,   10,   26,   25,   26,   26,   26,   27,  229,   27,
       27,   27,   45,   42,   26,   42,  100,   26,   52,   27,
      110,   42,   33,  228,   33,   52,   26,  110,   33,  226,
       52,   27,  110,   33,  172,   33,   85,   85,   68,   68,
       68,  172,   26,   57,  116,  116,   57,   57,   68,   68,
       73,  225,   73,   73,   73,  223,   57,   57,  117,  117,
       68,   68,   73,   76,  221,   76,   76,  219,   76,   76,
       76,   57,  155,  155,   73,   57,   72,   72,   72,   57,
      131,  131,  131,  218,  216,   57,   72,   72,   57,  214,
       57,  213,   57,   74,   57,   74,   74,   74,   72,   72,

       78,  212,   78,   78,   78,   74,  211,  210,  126,  209,
      126,  208,   78,  126,  126,  126,  207,   74,   77,   77,
       77,  206,  205,  204,   78,  203,  201,   77,   77,   77,
       77,   77,  200,  199,  198,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,  125,
      125,  125,  130,  130,  130,  197,  196,  193,  125,  125,
      125,  191,  130,  130,  190,  189,  187,  125,  125,  125,
      125,  125,  125,  186,  130,  130,  132,  185,  132,  132,
      132,  184,  159,  159,  159,  183,  178,  176,  175,  132,

      173,  170,  166,  159,  165,  164,  163,  161,  160,  157,
      154,  132,  134,  134,  134,  159,  153,  152,  151,  150,
      149,  134,  134,  134,  148,  147,  144,  143,  142,  141,
      134,  134,  134,  134,  134,  134,  233,  233,  233,  233,
      233,  233,  233,  234,  234,  234,  234,  234,  234,  234,
      235,  235,  235,  235,  235,  235,  235,  236,  236,  236,
      237,  237,  238,  238,  238,  140,  238,  238,  238,  239,
      239,  239,  239,  239,  239,  239,  240,  139,  138,  240,
      240,  240,  240,  241,  137,  241,  241,  241,  241,  241,
      242,  242,  242,  242,  242,  242,  242,  136,  135,  128,

      106,  105,  104,  103,  102,  101,   99,   98,   95,   94,
       93,   92,   90,   87,   86,   84,   83,   75,   70,   60,
       53,   51,   48,   47,   46,   44,   43,   39,   38,   36,
       32,   31,   30,   20,   15,   14,   11,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "flex_rules.l"
#define INITIAL 0
/*Опции*/
#define YY_NEVER_INTERACTIVE 1
/*Именованные шаблоны*/
/*Стартовые состояния*/
#define MULTILINE_COMMENT 1

#define STRING_SC 2

#define CHAR_SC 3

#define NSSTRING_SC 4

/*Подключение библиотек*/
#line 17 "flex_rules.l"
    #include "classes_nodes.h"
    #include "bison_rules_with_code_tab.h"
    #include <stdio.h>
    #include <string.h>
    #include <stdlib.h>
    #include <iostream>
    #include <fstream>
    extern int yyparse(void);
    extern Program_node *root;
    extern set<string> ClassNames;
    int isContainsSymbol(char *string, char symbol);
    void removeSymbol(char *string, char symbol);
    void removeFloatSuffix(char *string);
    int countChar(const char *str, char character);
#line 582 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 33 "flex_rules.l"


    char tmp[10000];
    int lineCount = 1;
    std::string str = "";




#line 739 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 233 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 438 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 42 "flex_rules.l"
{printf("Found keyword INT: %s\n", yytext);   return INT;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 43 "flex_rules.l"
{printf("Found keyword CHAR: %s\n", yytext);     return CHAR;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 44 "flex_rules.l"
{printf("Found keyword IF: %s\n", yytext);     return IF;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 45 "flex_rules.l"
{printf("Found keyword ELSE: %s\n", yytext);     return ELSE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "flex_rules.l"
{printf("Found keyword WHILE: %s\n", yytext);   return WHILE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "flex_rules.l"
{printf("Found keyword DO: %s\n", yytext);     return DO;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "flex_rules.l"
{printf("Found keyword FOR: %s\n", yytext);   return FOR;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "flex_rules.l"
{printf("Found keyword IN: %s\n", yytext);     return IN;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "flex_rules.l"
{printf("Found keyword INTERFACE: %s\n", yytext);      return INTERFACE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 51 "flex_rules.l"
{printf("Found keyword END: %s\n", yytext);      return END;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "flex_rules.l"
{printf("Found keyword IMPLEMENTATION: %s\n", yytext);    return IMPLEMENTATION;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "flex_rules.l"
{printf("Found keyword PROPERTY: %s\n", yytext);    return PROPERTY;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "flex_rules.l"
{printf("Found keyword SYNTHESIZE: %s\n", yytext);    return SYNTHESIZE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "flex_rules.l"
{printf("Found keyword FLOAT: %s\n", yytext);       return FLOAT;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "flex_rules.l"
{printf("Found keyword READONLY: %s\n", yytext);     return READONLY;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "flex_rules.l"
{printf("Found keyword READWRITE: %s\n", yytext);   return READWRITE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "flex_rules.l"
{printf("Found keyword ENUM: %s\n", yytext);     return ENUM;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "flex_rules.l"
{printf("Found keyword UNSIGNED: %s\n", yytext);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "flex_rules.l"
{printf("Found suffix U: %s\n", yytext);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "flex_rules.l"
{printf("Found keyword LONG: %s\n", yytext);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "flex_rules.l"
{printf("Found suffix L: %s\n", yytext);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "flex_rules.l"
{printf("Found keyword RETURN: %s\n", yytext);     return RETURN;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "flex_rules.l"
{printf("Found keyword SELF: %s\n", yytext);     return SELF;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "flex_rules.l"
{printf("Found keyword SUPER: %s\n", yytext);   return SUPER;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "flex_rules.l"
{printf("Found keyword ID: %s\n", yytext);     return ID;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "flex_rules.l"
{printf("Found keyword CLASS: %s\n", yytext);  return CLASS;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "flex_rules.l"
{printf("Found keyword VOID: %s\n", yytext);     return VOID;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 72 "flex_rules.l"
{printf("Found arithmetic operation +: %s\n", yytext);  return (unsigned char)'+';}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 73 "flex_rules.l"
{printf("Found arithmetic operation -: %s\n", yytext);  return (unsigned char)'-';}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 74 "flex_rules.l"
{printf("Found arithmetic operation *: %s\n", yytext);  return (unsigned char)'*';}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 75 "flex_rules.l"
{printf("Found arithmetic operation /: %s\n", yytext);  return (unsigned char)'/';}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 76 "flex_rules.l"
{printf("ERROR! Unsupported operation '++': %s\n", yytext);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 77 "flex_rules.l"
{printf("ERROR! Unsupported operation '--': %s\n", yytext);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 79 "flex_rules.l"
{printf("Found comparison operation ==: %s\n", yytext);    return EQUAL;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 80 "flex_rules.l"
{printf("Found comparison operation !=: %s\n", yytext);    return NOT_EQUAL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 81 "flex_rules.l"
{printf("Found comparison operation >: %s\n", yytext);      return (unsigned char)'>';}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 82 "flex_rules.l"
{printf("Found comparison operation <: %s\n", yytext);      return (unsigned char)'<';}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 83 "flex_rules.l"
{printf("Found comparison operation >=: %s\n", yytext);    return GREATER_EQUAL;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 84 "flex_rules.l"
{printf("Found comparison operation <=: %s\n", yytext);    return LESS_EQUAL;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 87 "flex_rules.l"
{printf("Found assignment operation =: %s\n", yytext);      return (unsigned char)'=';}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 88 "flex_rules.l"
{printf("ERROR! Unsupported operation '+=': %s\n", yytext);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 89 "flex_rules.l"
{printf("ERROR! Unsupported operation '-=': %s\n", yytext);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 90 "flex_rules.l"
{printf("ERROR! Unsupported operation '*=': %s\n", yytext);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 91 "flex_rules.l"
{printf("ERROR! Unsupported operation '/=': %s\n", yytext);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 93 "flex_rules.l"
{printf("Found member access operator '.' %s\n", yytext);   return (unsigned char)'.';}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 94 "flex_rules.l"
{printf("Found member access operator '->' %s\n", yytext);     return ARROW;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 97 "flex_rules.l"
{printf("Found bracket (: %s\n", yytext);   return (unsigned char)'(';}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 98 "flex_rules.l"
{printf("Found bracket ): %s\n", yytext);   return (unsigned char)')';}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 99 "flex_rules.l"
{printf("Found bracket {: %s\n", yytext);   return (unsigned char)'{';}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 100 "flex_rules.l"
{printf("Found bracket }: %s\n", yytext);   return (unsigned char)'}';}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 101 "flex_rules.l"
{printf("Found bracket [: %s\n", yytext);   return (unsigned char)'[';}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 102 "flex_rules.l"
{printf("Found bracket ]: %s\n", yytext);   return (unsigned char)']';}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 105 "flex_rules.l"
{printf("Found delimiter ;: %s\n", yytext);     return (unsigned char)';';}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 106 "flex_rules.l"
{printf("Found delimiter :: %s\n", yytext);     return (unsigned char)':';}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 107 "flex_rules.l"
{printf("Found delimiter ,: %s\n", yytext);     return (unsigned char)',';}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 109 "flex_rules.l"
{printf("Found integer: %d\n", atoi(yytext));   yylval.Integer_constant=atoi(yytext); return INTEGER_CONSTANT;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 110 "flex_rules.l"
{
    char* a;
    long number = strtol(yytext+2, &a,16);
    printf("Found hexadecimal number: %d\n", number);
    yylval.Integer_constant=number;
    return INTEGER_CONSTANT;
    }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 117 "flex_rules.l"
{
    printf("ERROR! Incorrect hex number: %s in row: %d\n", yytext, lineCount);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 120 "flex_rules.l"
{
    char *a;
    long number = strtol(yytext+2, &a,8);
    printf("Found octal number: %d\n", number);
    yylval.Integer_constant=number;
    return INTEGER_CONSTANT;
    }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 127 "flex_rules.l"
{
    printf("ERROR! Incorrect octal number: %s in row: %d\n", yytext, lineCount);
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 131 "flex_rules.l"
{str = ""; BEGIN(CHAR_SC);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 132 "flex_rules.l"
{str = ""; BEGIN(STRING_SC);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 133 "flex_rules.l"
{str = ""; BEGIN(NSSTRING_SC);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 134 "flex_rules.l"
{str += yytext;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 135 "flex_rules.l"
{str += yytext;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 136 "flex_rules.l"
{str += "\b";}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 137 "flex_rules.l"
{str += "\f";}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 138 "flex_rules.l"
{str += "\n";}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 139 "flex_rules.l"
{str += "\r";}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 140 "flex_rules.l"
{str += "\t";}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 141 "flex_rules.l"
{str += "\v";}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 142 "flex_rules.l"
{str += "\'";}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 143 "flex_rules.l"
{str += "\"";}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 144 "flex_rules.l"
{str += "\\";}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 145 "flex_rules.l"
{str += '\0';}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 146 "flex_rules.l"
{str += '\0';}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 147 "flex_rules.l"
{str += '\0';}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 148 "flex_rules.l"
{
    char *a;
    char c =strtol(yytext+2, &a, 16);
    str += c;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 152 "flex_rules.l"
{printf("ERROR! Incorrect hex digit in string.\n");}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 153 "flex_rules.l"
{
    char *a;
    char c =strtol(yytext+1, &a, 8);
    str += c;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 157 "flex_rules.l"
{printf("ERROR! Multiline string\n"); lineCount++;}
	YY_BREAK
case YY_STATE_EOF(STRING_SC):
case YY_STATE_EOF(CHAR_SC):
case YY_STATE_EOF(NSSTRING_SC):
#line 158 "flex_rules.l"
{printf("ERROR! haven't found closing quotes.\n"); BEGIN(INITIAL);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 159 "flex_rules.l"
{std::cout << "Found String literal: " << str.c_str() << std::endl;

      if (YY_START == STRING_SC)
      {
        yylval.String_constant = new char[str.length()];
        strcpy(yylval.String_constant, str.c_str()); 
        BEGIN(INITIAL);
        return STRING_CONSTANT;
      }
      else
      {
        yylval.NSString_constant = new char[str.length()];
        strcpy(yylval.NSString_constant, str.c_str()); 
        BEGIN(INITIAL);
        return NSSTRING_CONSTANT;
      }

}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 177 "flex_rules.l"
{
    if(str.size() != 1)
    {
        printf("ERROR! char length != 1 in row: %d. Char length: %d\n", lineCount, str.size());BEGIN(INITIAL);
    }
    else
    {
        std::cout << "Found char: " + str << std::endl;BEGIN(INITIAL);
        yylval.Char_constant = new char[str.length()];
        strcpy(yylval.Char_constant, str.c_str());
        BEGIN(INITIAL);
        return CHAR_CONSTANT;
    }
    
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 195 "flex_rules.l"
{
    strcpy(tmp, yytext);
    removeFloatSuffix(tmp);
    printf("Found float constant: %f\n", (float)atof(tmp));
    yylval.Float_constant = (float)atof(tmp);
    return FLOAT_CONSTANT;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 203 "flex_rules.l"
{
    strcpy(tmp, yytext);
    removeFloatSuffix(tmp);
    printf("Found float constant: %f\n", (float)atof(tmp));
    yylval.Float_constant = (float)atof(tmp);
    return FLOAT_CONSTANT;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 211 "flex_rules.l"
{printf("Found identifier: %s\n", yytext);
    str = "";
    str += yytext;
    yylval.Identifier = new char[str.length()];
    strcpy(yylval.Identifier, str.c_str());
    if (ClassNames.count(str))
        return CLASS_NAME;
    else
        return IDENTIFIER;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 221 "flex_rules.l"
{printf("ERROR! Incorrect identifier: %s\n", yytext);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 224 "flex_rules.l"
{printf("Found line comment: %s\n", yytext);
    strcpy(tmp, yytext);
    lineCount += countChar(tmp, '\n');
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 230 "flex_rules.l"
{tmp[0] = '\0'; BEGIN(MULTILINE_COMMENT);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 231 "flex_rules.l"
{strcat(tmp, yytext);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 232 "flex_rules.l"
{lineCount++; strcat(tmp, yytext);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 233 "flex_rules.l"
{strcat(tmp, yytext);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 234 "flex_rules.l"
{lineCount++; strcat(tmp, yytext);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 235 "flex_rules.l"
{printf("Found multiline comment: %s\n", tmp);BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 237 "flex_rules.l"
{printf("ERROR! Multiline comment \"%s\" isn't closed in row: %d\n", tmp, lineCount); BEGIN(INITIAL);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 239 "flex_rules.l"
{printf("");}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 241 "flex_rules.l"
{lineCount++;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 242 "flex_rules.l"
{lineCount++;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 244 "flex_rules.l"
{printf("unrecognized element: %s\n", yytext);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 246 "flex_rules.l"
ECHO;
	YY_BREAK
#line 1404 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 233 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 233 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 232);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 246 "flex_rules.l"


//Проверка на содержание символа в строке
int isContainsSymbol(char *string, char symbol)
{
    return strchr(string, symbol) != NULL;
}

//Удаление первого вхождения символа в строку
void removeSymbol(char *string, char symbol)
{
    if (isContainsSymbol(string, symbol))
    {
        char* pointer = strchr(string, symbol);
        int symbolPos = pointer - string;
        int len = strlen(string);
        for (int i=symbolPos; i < len; i++)
        {
            string[i] = string[i+1];
        }
        string[len-1] = '\0';
    }
}

//Удаление суффикса float
void removeFloatSuffix(char *string)
{
    if (isContainsSymbol(string, 'f') || isContainsSymbol(string, 'F'))
    {
        removeSymbol(string, 'f');
        removeSymbol(string, 'F');
    }
}

//Количество вхождения символа в строку
int countChar(const char *str, char character)
{
    int count = 0;
    int len = strlen(str);
    for (int i=0; i<len; i++)
    {
        if (str[i] == character)
            count++;
    }
    return count;
}

int main(int argc, char* argv[])
{
    if ( argc > 1 )
            yyin = fopen( argv[1], "r" );
    else
            yyin = stdin;

    yyparse();

    string res = root->toDot();
    ofstream out("dot.dot");
    out << res;
    out.close();
}
