/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <crtdbg.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
static yyconst short int yy_accept[221] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       96,   94,   93,   91,   94,   58,   57,   43,   44,   26,
       24,   51,   25,   41,   27,   52,   52,   50,   49,   33,
       36,   32,   94,   82,   47,   94,   48,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   45,   46,   86,   94,
       86,   60,   77,   78,   94,   61,   79,   91,   31,   39,
       28,   37,   29,   38,   42,   80,   85,   84,   40,   80,
       55,   56,   83,   83,   83,   52,   35,   30,   34,   59,
        0,    0,    0,    0,    0,   82,   92,   82,    6,   82,
       82,   82,   82,   21,    3,    8,   82,   82,   82,   82,

       82,   86,   87,   88,   89,    0,   90,   87,   60,   69,
       68,   71,   76,   70,   62,   63,   64,   65,   66,   67,
       75,    0,   80,   84,   84,   80,    0,   81,   53,   54,
        0,    0,    0,    0,    0,    0,   82,   82,   82,   82,
        7,    1,   82,   82,   82,   82,   82,   82,   76,   75,
       72,   74,   81,   81,    0,   10,    0,    0,    0,    0,
        2,    4,   17,   82,   82,   82,   19,   82,   23,   82,
       76,   73,   74,   81,    0,    0,    0,    0,    0,   14,
       82,   82,   82,   20,    5,   22,    0,    0,    0,    0,
       82,   82,   18,    0,    0,    0,    0,   82,   82,    0,

        0,    0,    0,   15,   82,    0,    0,   12,    0,   16,
        0,    9,    0,    0,   13,    0,    0,    0,   11,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    1,    1,    1,    1,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   17,   17,   18,   19,   20,
       21,   22,    1,   23,   24,   24,   24,   24,   25,   26,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   28,   27,   27,
       29,   30,   31,    1,   32,    1,   33,   34,   35,   36,

       37,   38,   27,   39,   40,   27,   27,   41,   42,   43,
       44,   45,   27,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,    1,   56,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[57] =
    {   0,
        1,    2,    1,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    5,    1,    6,    6,    6,    1,    1,    1,
        1,    1,    1,    6,    6,    6,    7,    7,    1,    3,
        1,    7,    6,    6,    6,    6,    6,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    1,    1
    } ;

static yyconst short int yy_base[232] =
    {   0,
        0,    0,   55,   56,   57,   58,   64,   65,   67,   71,
      425,  426,  426,  421,  402,  426,  426,  426,  426,  401,
       58,  426,   62,   65,   82,   89,   94,  426,  426,  400,
      399,  398,   85,    0,  426,  416,  426,  378,  372,   34,
       48,   80,  378,   63,  370,  374,  426,  426,  410,  119,
      409,    0,  426,  426,  140,  426,  426,  407,  426,  426,
      426,  426,  426,  426,  426,  122,  426,  379,  426,  147,
      152,  178,  395,  189,  201,  194,  426,  426,  426,  426,
      366,  363,   56,  359,  351,    0,  426,  370,    0,  355,
      352,  356,  353,    0,    0,  338,   45,  339,  334,  327,

      291,  328,  426,  426,  426,  152,  426,  426,    0,  426,
      426,  119,  128,  426,  426,  426,  426,  426,  426,  426,
      241,  270,  426,  299,  106,  246,  134,  275,    0,  299,
      295,  291,  281,  274,  277,  277,  273,  281,  270,  278,
        0,    0,  274,  260,  270,  270,  270,  263,  137,  426,
      288,    0,  279,  289,  253,  426,  258,  261,  252,  245,
        0,    0,    0,  241,  131,  235,    0,  227,    0,  233,
      426,  426,  426,  426,  222,  231,  218,  223,  220,    0,
      189,  184,  181,    0,    0,  426,  181,  184,  175,  183,
      173,  173,    0,  175,  175,  152,  151,  144,  148,  144,

      146,  127,  139,    0,  139,  123,  121,  426,  103,    0,
      107,  426,   92,   79,  426,   84,   71,   70,  426,  426,
      337,  344,  351,  354,  356,  363,  370,  377,  384,  391,
       55
    } ;

static yyconst short int yy_def[232] =
    {   0,
      220,    1,  221,  221,  222,  222,  223,  223,  222,  222,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  224,  224,  220,  220,  220,
      220,  220,  220,  225,  220,  220,  220,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  220,  220,  226,  227,
      226,  228,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  229,  220,  220,
      224,  224,  224,  224,  220,  224,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  225,  220,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,

      225,  226,  220,  220,  220,  227,  220,  220,  228,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      230,  220,  220,  229,  229,  220,  220,  224,   75,   75,
      220,  220,  220,  220,  220,  220,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  220,  220,
      231,  231,  220,  224,  220,  220,  220,  220,  220,  220,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  225,
      225,  225,  225,  225,  225,  220,  220,  220,  220,  220,
      225,  225,  225,  220,  220,  220,  220,  225,  225,  220,

      220,  220,  220,  225,  225,  220,  220,  220,  220,  225,
      220,  220,  220,  220,  220,  220,  220,  220,  220,    0,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220
    } ;

static yyconst short int yy_nxt[483] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   27,   28,   29,   30,
       31,   32,   33,   34,   34,   34,   34,   34,   35,   36,
       37,   34,   34,   34,   38,   39,   40,   41,   34,   42,
       34,   34,   34,   34,   34,   43,   44,   34,   34,   45,
       46,   34,   34,   34,   47,   48,   13,   13,   53,   53,
      173,   54,   54,   50,   50,   53,   53,   61,   53,   57,
       57,   54,   53,   63,   90,   54,   91,  143,   62,   66,
       66,   66,   64,   65,   51,   51,   55,   55,   92,   80,
       67,   93,  144,   55,   55,   68,   55,  133,  134,   98,

       55,   70,   69,   71,   71,   72,   70,  124,   76,   76,
       76,   99,  219,   74,  218,   94,   75,   95,   74,   81,
      105,   82,   96,  217,   83,   74,  216,  106,  215,   84,
       74,   85,  107,  149,  149,  125,   66,   66,   66,  214,
       75,   87,  149,  149,  110,  111,  122,  123,  153,  153,
      153,  171,  171,  105,  112,  113,  213,  212,  122,  123,
      106,  126,  126,  126,   70,  107,   71,   71,   72,  114,
      211,  122,  123,  115,  181,  210,   74,  116,  209,  208,
      207,  182,  117,  122,  123,  118,  206,  119,   74,  120,
       70,  121,   72,   72,   72,  205,  204,  203,  127,  202,

      127,  220,   74,  128,  128,  128,   70,  201,   76,   76,
       76,  200,  199,  198,   74,  129,  129,  129,   74,  197,
      196,  195,  194,  193,  129,  129,  129,  130,  130,  192,
       74,  191,   73,  129,  129,  129,  129,  129,  129,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  151,  152,  152,  190,  189,
      126,  126,  126,  188,  152,  152,  152,  187,  186,  185,
      122,  123,  184,  152,  152,  152,  152,  152,  152,  127,
      183,  127,  122,  123,  153,  153,  153,  220,  180,  128,
      128,  128,  179,  153,  153,  153,  178,  177,  176,  175,

      154,  220,  172,  170,  174,  169,  168,  167,  166,  165,
      164,  163,  154,  130,  130,  130,  174,  162,  161,  160,
      159,  158,  130,  130,  130,  157,  156,  155,  125,  103,
      148,  130,  130,  130,  130,  130,  130,   49,   49,   49,
       49,   49,   49,   49,   52,   52,   52,   52,   52,   52,
       52,   56,   56,   56,   56,   56,   56,   56,   73,   73,
       73,   86,   86,  102,  102,  102,  147,  102,  102,  102,
      104,  104,  104,  104,  104,  104,  104,  109,  146,  145,
      109,  109,  109,  109,  124,  142,  124,  124,  124,  124,
      124,  150,  150,  150,  150,  150,  150,  150,  141,  140,

      139,  138,  137,  136,  135,  132,  131,  220,  125,   58,
      108,  103,  101,  100,   97,   89,   88,   87,   79,   78,
       77,   60,   59,   58,  220,   11,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220
    } ;

static yyconst short int yy_chk[483] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    5,    6,
      231,    5,    6,    3,    4,    7,    8,   21,    9,    7,
        8,    9,   10,   23,   40,   10,   40,   97,   21,   24,
       24,   24,   23,   23,    3,    4,    5,    6,   41,   33,
       25,   41,   97,    7,    8,   25,    9,   83,   83,   44,

       10,   26,   25,   26,   26,   26,   27,  125,   27,   27,
       27,   44,  218,   26,  217,   42,   26,   42,   27,   33,
       50,   33,   42,  216,   33,   26,  214,   50,  213,   33,
       27,   33,   50,  112,  112,  125,   66,   66,   66,  211,
       26,   55,  113,  113,   55,   55,   66,   66,  127,  127,
      127,  149,  149,  106,   55,   55,  209,  207,   66,   66,
      106,   70,   70,   70,   71,  106,   71,   71,   71,   55,
      206,   70,   70,   55,  165,  205,   71,   55,  203,  202,
      201,  165,   55,   70,   70,   55,  200,   55,   71,   55,
       72,   55,   72,   72,   72,  199,  198,  197,   74,  196,

       74,   74,   72,   74,   74,   74,   76,  195,   76,   76,
       76,  194,  192,  191,   72,   75,   75,   75,   76,  190,
      189,  188,  187,  183,   75,   75,   75,   75,   75,  182,
       76,  181,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,  121,  121,  121,  179,  178,
      126,  126,  126,  177,  121,  121,  121,  176,  175,  170,
      126,  126,  168,  121,  121,  121,  121,  121,  121,  122,
      166,  122,  126,  126,  122,  122,  122,  128,  164,  128,
      128,  128,  160,  153,  153,  153,  159,  158,  157,  155,

      128,  154,  151,  148,  153,  147,  146,  145,  144,  143,
      140,  139,  128,  130,  130,  130,  153,  138,  137,  136,
      135,  134,  130,  130,  130,  133,  132,  131,  124,  102,
      101,  130,  130,  130,  130,  130,  130,  221,  221,  221,
      221,  221,  221,  221,  222,  222,  222,  222,  222,  222,
      222,  223,  223,  223,  223,  223,  223,  223,  224,  224,
      224,  225,  225,  226,  226,  226,  100,  226,  226,  226,
      227,  227,  227,  227,  227,  227,  227,  228,   99,   98,
      228,  228,  228,  228,  229,   96,  229,  229,  229,  229,
      229,  230,  230,  230,  230,  230,  230,  230,   93,   92,

       91,   90,   88,   85,   84,   82,   81,   73,   68,   58,
       51,   49,   46,   45,   43,   39,   38,   36,   32,   31,
       30,   20,   15,   14,   11,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
#define INITIAL 0
/*Опции*/
#define YY_NEVER_INTERACTIVE 1
/*Именованные шаблоны*/
/*Стартовые состояния*/
#define MULTILINE_COMMENT 1

#define STRING_SC 2

#define CHAR_SC 3

#define NSSTRING_SC 4

/*Подключение библиотек*/
#line 17 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
    #include "tables.h"
    #include "bison_rules_with_code_tab.h"
    #include <stdio.h>
    #include <string.h>
    #include <stdlib.h>
    #include <iostream>
    #include <fstream>
    #include <filesystem>
    extern int yyparse(void);
    extern Program_node *root;
    extern set<string> ClassNames;
    int isContainsSymbol(char *string, char symbol);
    void removeSymbol(char *string, char symbol);
    void removeFloatSuffix(char *string);
    int countChar(const char *str, char character);
    int lineCount = 1;
#line 576 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 35 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"


    char tmp[10000];
    std::string str = "";




#line 732 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 221 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 426 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 43 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return INT;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 44 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return CHAR;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return IF;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 46 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return ELSE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 47 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return WHILE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return DO;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return FOR;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return IN;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 51 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return INTERFACE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 52 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return END;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 53 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return IMPLEMENTATION;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Unsupported property: %s\n", yytext); return -1;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Unsupported property: %s\n", yytext); return -1;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Unsupported type float: %s\n", yytext); return -1;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 57 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Unsupported property: %s\n", yytext); return -1;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 58 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Unsupported property: %s\n", yytext); return -1;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return ENUM;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 60 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return RETURN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 61 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return SELF;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 62 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return SUPER;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return ID;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return CLASS;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return VOID;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 69 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)'+';}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 70 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)'-';}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 71 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)'*';}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 72 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)'/';}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 73 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Unsupported operation '++': %s\n", yytext); return -1;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 74 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Unsupported operation '--': %s\n", yytext); return -1;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 76 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return EQUAL;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 77 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return NOT_EQUAL;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 78 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)'>';}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 79 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)'<';}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 80 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return GREATER_EQUAL;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 81 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return LESS_EQUAL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 84 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)'=';}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 85 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Unsupported operation '+=': %s\n", yytext); return -1;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 86 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Unsupported operation '-=': %s\n", yytext); return -1;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 87 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Unsupported operation '*=': %s\n", yytext); return -1;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 88 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Unsupported operation '/=': %s\n", yytext); return -1;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 90 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Unsupported property access operation: %s\n", yytext); return -1;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 91 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return ARROW;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 94 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)'(';}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 95 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)')';}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 96 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)'{';}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 97 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)'}';}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 98 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)'[';}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 99 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)']';}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 102 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)';';}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 103 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)':';}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 104 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{return (unsigned char)',';}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 106 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{yylval.Integer_constant=atoi(yytext); return INTEGER_CONSTANT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 107 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    char* a;
    long number = strtol(yytext+2, &a,16);
    yylval.Integer_constant=number;
    return INTEGER_CONSTANT;
    }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 113 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    printf("ERROR! Incorrect hex number: %s in row: %d\n", yytext, lineCount);
    return -1;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    char *a;
    long number = strtol(yytext+2, &a,8);
    yylval.Integer_constant=number;
    return INTEGER_CONSTANT;
    }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 123 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    printf("ERROR! Incorrect octal number: %s in row: %d\n", yytext, lineCount);
    return -1;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 128 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str = ""; BEGIN(CHAR_SC);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 129 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str = ""; BEGIN(STRING_SC);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 130 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str = ""; BEGIN(NSSTRING_SC);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 131 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str += yytext;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 132 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str += yytext;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 133 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str += "\b";}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 134 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str += "\f";}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 135 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str += "\n";}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 136 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str += "\r";}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 137 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str += "\t";}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 138 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str += "\v";}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 139 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str += "\'";}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 140 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str += "\"";}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 141 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str += "\\";}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 142 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str += '\0';}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 143 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str += '\0';}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 144 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{str += '\0';}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 145 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    char *a;
    char c =strtol(yytext+2, &a, 16);
    str += c;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 149 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Incorrect hex digit in string.\n"); return -1;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 150 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    char *a;
    char c =strtol(yytext+1, &a, 8);
    str += c;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 154 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Multiline string\n"); lineCount++; return -1;}
	YY_BREAK
case YY_STATE_EOF(STRING_SC):
case YY_STATE_EOF(CHAR_SC):
case YY_STATE_EOF(NSSTRING_SC):
#line 155 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! haven't found closing quotes.\n"); BEGIN(INITIAL); return -1;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 156 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{

      if (YY_START == STRING_SC)
      {
        yylval.String_constant = new char[str.length()];
        strcpy(yylval.String_constant, str.c_str()); 
        BEGIN(INITIAL);
        return STRING_CONSTANT;
      }
      else
      {
        yylval.NSString_constant = new char[str.length()];
        strcpy(yylval.NSString_constant, str.c_str()); 
        BEGIN(INITIAL);
        return NSSTRING_CONSTANT;
      }

}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 174 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    if(str.size() != 1)
    {
        printf("ERROR! char length != 1 in row: %d. Char length: %d\n", lineCount, str.size());BEGIN(INITIAL); return -1;
    }
    else
    {
        yylval.Char_constant = new char[str.length()];
        strcpy(yylval.Char_constant, str.c_str());
        BEGIN(INITIAL);
        return CHAR_CONSTANT;
    }
    
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 191 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    // strcpy(tmp, yytext);
    // removeFloatSuffix(tmp);
    // printf("Found float constant: %f\n", (float)atof(tmp));
    // yylval.Float_constant = (float)atof(tmp);
    // return FLOAT_CONSTANT;

    printf("ERROR! Unsupported type float: %s\n", yytext); return -1;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 201 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    // strcpy(tmp, yytext);
    // removeFloatSuffix(tmp);
    // printf("Found float constant: %f\n", (float)atof(tmp));
    // yylval.Float_constant = (float)atof(tmp);
    // return FLOAT_CONSTANT;

    printf("ERROR! Unsupported type float: %s\n", yytext); return -1;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 211 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    str = "";
    str += yytext;
    yylval.Identifier = new char[str.length()];
    strcpy(yylval.Identifier, str.c_str());
    if (ClassNames.count(str))
        return CLASS_NAME;
    else
        return IDENTIFIER;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 221 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Incorrect identifier: %s\n", yytext); return -1;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 224 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{
    strcpy(tmp, yytext);
    lineCount += countChar(tmp, '\n');
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 230 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{tmp[0] = '\0'; BEGIN(MULTILINE_COMMENT);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 231 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{strcat(tmp, yytext);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 232 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{lineCount++; strcat(tmp, yytext);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 233 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{strcat(tmp, yytext);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 234 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{lineCount++; strcat(tmp, yytext);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 235 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 237 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("ERROR! Multiline comment \"%s\" isn't closed in row: %d\n", tmp, lineCount); BEGIN(INITIAL); return -1;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 239 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("");}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 241 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{lineCount++;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 242 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{lineCount++;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 244 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
{printf("unrecognized element: %s\n", yytext); return -1;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 246 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"
ECHO;
	YY_BREAK
#line 1380 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 221 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 221 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 220);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 246 "D:\\C projects\\Compiler\\objective_c_compiler\\flex_rules.l"


//Проверка на содержание символа в строке
int isContainsSymbol(char *string, char symbol)
{
    return strchr(string, symbol) != NULL;
}

//Удаление первого вхождения символа в строку
void removeSymbol(char *string, char symbol)
{
    if (isContainsSymbol(string, symbol))
    {
        char* pointer = strchr(string, symbol);
        int symbolPos = pointer - string;
        int len = strlen(string);
        for (int i=symbolPos; i < len; i++)
        {
            string[i] = string[i+1];
        }
        string[len-1] = '\0';
    }
}

//Удаление суффикса float
void removeFloatSuffix(char *string)
{
    if (isContainsSymbol(string, 'f') || isContainsSymbol(string, 'F'))
    {
        removeSymbol(string, 'f');
        removeSymbol(string, 'F');
    }
}

//Количество вхождения символа в строку
int countChar(const char *str, char character)
{
    int count = 0;
    int len = strlen(str);
    for (int i=0; i<len; i++)
    {
        if (str[i] == character)
            count++;
    }
    return count;
}

int main(int argc, char* argv[])
{
   if ( argc > 1 )
        yyin = fopen( argv[1], "r" );
else
        yyin = stdin;

printf("Start parsing\n");
int parseRes = yyparse(); //Синтаксический разбор
if (parseRes == 0) {
    printf("Successful parsing\n");

	bool isPreviousSuccess = true;

	//Построение dot дерева до семантического анализа
	if (isPreviousSuccess) {
		try {
			printf("Start generating dot file before semantic analysis\n");
			string res = root->toDot();
			ofstream out("dot_before.dot");
			out << res;
			out.close();
			printf("Successful generating dot file before semantic analysis\n");
		}
		catch (...) {
			printf("Failed generating dot file before semantic analysis\n");
			isPreviousSuccess = false;
		}
	}
    
	//Семантический анализ
	if (isPreviousSuccess) {
		try {
			printf("Start semantic analysis\n");
			root->fillClassesTable();
			printf("Successful semantic analysis\n");
		}
		catch (std::exception *e) {
			printf("%s", e->what());
			isPreviousSuccess = false;
		}
		catch (...) {
			printf("Failed semantic analysis\n");
			isPreviousSuccess = false;
		}
		
	}

	// Вывод таблиц после семантического анализа
	if (isPreviousSuccess) {
		try {
			printf("Start printing tables after semantic analysis\n");
			filesystem::path p = filesystem::path("./out/tables/");
			filesystem::remove_all(p);
			filesystem::create_directory(p);
			ClassesTable::toCsvFile("./out/tables/");
			FunctionsTable::toCsvFile("FunctionsTable.csv", "./out/tables/");
			printf("Successful printing tables after semantic analysis\n");
		}
		catch (...) {
			printf("Failed printing tables after semantic analysis\n");
			isPreviousSuccess = false;
		}
	}

	//Построение dot дерева после семантического анализа
	if (isPreviousSuccess) {
		try {
			printf("Start generating dot file after semantic analysis\n");
			string res = root->toDot();
			ofstream out("dot_after.dot");
			out << res;
			out.close();
			printf("Successful generating dot file after semantic analysis\n");
		}
		catch (...) {
			printf("Failed generating dot file after semantic analysis\n");
			isPreviousSuccess = false;
		}
	}

	//Генерация .class файлов
	if (isPreviousSuccess) {
		try {
			printf("Start code generation\n");
			filesystem::path p = filesystem::path("./out/code/global/");
			filesystem::remove_all(p);
			filesystem::create_directory(p);
			ClassesTable::generateClassFiles("./out/code/");
			printf("Successful code generation\n");
		}
		catch (...) {
			printf("Failed code generation\n");
			isPreviousSuccess = false;
		}
	}


	//Генерация .jar файла
	if (isPreviousSuccess) {
		try {
			printf("Start generating .jar file\n");
			string manifest = "main-class: rtl.Program\nclass-path: code/\n";
			ofstream out("./out/manifest.mf");
			out << manifest;
			out.close();
			string jar = "cd ./out/ && jar -cmf manifest.mf code.jar -C code .";
			system(jar.c_str());
			string runBat = "@echo off\njava -noverify -jar code.jar";
			ofstream outBat("./out/run.bat");
			outBat << runBat;
			outBat.close();

			printf("Successful generating .jar file\n");
		}
		catch (...) {
			printf("Failed generating .jar file\n");
			isPreviousSuccess = false;
		}
	}
}
	_CrtSetReportMode(_CRT_ASSERT, _CRTDBG_MODE_DEBUG);
}
